#!/usr/bin/env bash

OUTPUT=${1:-bin/strike}
echo "Building strike ..."
mkdir -p bin

go get -u github.com/dgrijalva/jwt-go github.com/kavu/go_reuseport
go build -o $OUTPUT/strike cmd/strike/strike.go
cp -r examples $OUTPUT