#!/usr/bin/env bash

echo "Release alpine version ..."
mkdir -p bin/alpine
docker build -t go_alpine_builder -f Dockerfile.build.alpine .
docker run -ti --rm -v $(pwd):/app go_alpine_builder ./build bin/alpine/
ls -lh bin/*
tar -C bin/alpine/ -czf bin/alpine/strike-alpine-amd64.tar.gz strike mqgateway.json
